HA-92: Add "Update game" feature
skullizador/game-collector pull request #17
Opened 2023-01-20 18:31 UTC by SwarlosMigus5

@skullizador

2023-01-21 22:43 UTC, skullizador requested changes

2023-01-21 22:43 UTC, skullizador commented on src/Domain/AggregateModels/Competition/Game.cs
> +            this.Score = Score;
I believe score should only be updatable if a game already started.
May be add that validation here to protect the domain;

2023-01-21 22:43 UTC, skullizador commented on src/Presentation.WebAPI/Validation/Competition/UpdateGameDtoValidator.cs
> +            this.RuleFor(x => x.Score)
With the fact that a score should only be updated when the game already started, I think this rule can be removed.
Also you can create a rule to specificly verify if score is updatable or not

2023-01-22 13:59 UTC, SwarlosMigus5 commented on src/Presentation.WebAPI/Validation/Competition/UpdateGameDtoValidator.cs
> +            this.RuleFor(x => x.Score)
Do you think that making a bool type of method is a great approach to verifiy if the score is updatable?
bool method..
{
   if(StartDate.GreaterThan(DateTime.Now) == true)
      return true
}
What are your thoughts on this method?

2023-01-22 14:54 UTC, merged